import { Inter } from 'next/font/google'
import React from 'react'
import clsx from 'clsx'

import { RootLayout } from '@/app/components/RootLayout.client'
import { RootStyleRegistry } from '@/app/components/RootStyleRegistry.client'

import '@/styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'min-h-screen')}>
        <RootStyleRegistry>
          <RootLayout>{children}</RootLayout>
        </RootStyleRegistry>
      </body>
    </html>
  )
}
